export const headerListHistUser = [
  {
    title: {
      tit: "Territorio",
      fcolor: "",
      fsize: "16px",
      fw: 500,
    },
    with: 125,
    hight: 40,
    bc: "orange",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Recoge",
      fcolor: "",
      fsize: "16px",
      fw: 500,
    },
    with: 90,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Entrega",
      fcolor: "",
      fsize: "16px",
      fw: 500,
    },
    with: 90,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Dias uso",
      fcolor: "",
      fsize: "16px",
      fw: 500,
    },
    with: 70,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Estado",
      fcolor: "",
      fsize: "16px",
      fw: 500,
    },
    with: 80,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];

export const lineListHistUser = [
  {
    title: {
      tit: "Teritorio",
      fcolor: "",
      fsize: "13px",
      fw: 400,
    },
    with: 124,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Recoge",
      fcolor: "",
      fsize: "13px",
      fw: 400,
    },
    with: 91,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Entrega",
      fcolor: "",
      fsize: "13px",
      fw: 400,
    },
    with: 89,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "left",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Dias",
      fcolor: "",
      fsize: "13px",
      fw: 400,
    },
    with: 69,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Estado",
      fcolor: "",
      fsize: "13px",
    },
    with: 81,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];
