export const headerListTerr = [
  {
    title: {
      tit: "Zona",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 90,
    hight: 40,
    bc: "orange",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Código",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 70,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Estado",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 100,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Hermano que lo tiene",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 250,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Fecha Salida",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 120,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Fecha Entrada",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 130,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Periodo",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 120,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Acciones",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 80,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];

export const lineListTerr = [
  {
    title: {
      tit: "Zona",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 90,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Cod. Terr",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 70,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Estado",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 100,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Hermano que lo tiene",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 250,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "left",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Fecha Salida",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 120,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Fecha Entrada",
      fcolor: "",
      fsize: "14px",
    },
    with: 130,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Periodo",
      fcolor: "",
      fsize: "14px",
      fw: 500,
    },
    with: 120,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Acciones",
      fcolor: "bisque",
      fsize: "14px",
      fw: 500,
    },
    with: 80,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bol: "solid 1px rgb(79, 91, 121)",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];
