export const headerListUsers = [
  {
    title: {
      tit: "Código",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 70,
    hight: 40,
    bc: "orange",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Usuario",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 100,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Nombre",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 210,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Email",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 230,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Whatsapp",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 90,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Tipo",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 102,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 2px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Territorios",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 128,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Acciones",
      fcolor: "",
      fsize: "18px",
      fw: 500,
    },
    with: 86,
    hight: 40,
    bc: "orange",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];

export const lineListUsers = [
  {
    title: {
      tit: "Código",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 69,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bol: "solid 3px rgb(79, 91, 121)",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Usuario",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 99,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Nombre",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 207,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Email",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 227,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "left",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Whatsapp",
      fcolor: "",
      fsize: "14px",
      fw: 400,
    },
    with: 89,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Tipo",
      fcolor: "",
      fsize: "14px",
    },
    with: 101,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bor: "solid 1px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Territorios",
      fcolor: "",
      fsize: "14px",
    },
    with: 127,
    hight: 25,
    bc: "bisque",
    align: "center",
    bor: "solid 3px rgb(79, 91, 121)",
  },
  {
    title: {
      tit: "Acciones",
      fcolor: "bisque",
      fsize: "14px",
      fw: 500,
    },
    with: 86,
    hight: 25,
    bc: "bisque",
    bca: "rgb(254, 246, 236)",
    align: "center",
    bol: "solid 1px rgb(79, 91, 121)",
    bor: "solid 3px rgb(79, 91, 121)",
  },
];
